version: "3.8"

services: 
  db:
    image: mysql:latest 
    container_name: mydb 
    restart: unless-stopped
    environment: 
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: facial_reco 
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3308:3306'
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
     - "8082:80"
    environment:
      MYSQL_ROOT_PASSWORD: root #(Required) set the password for the root superuser account.
      PMA_HOST: db   # define the address/hostname of the mysql server eg mysql container name.
      PMA_USER: user # this is the root user to login on startup
      PMA_PASSWORD: root # use the root password to login on startup.


volumes: # add persistent data even if container is removed.
  my-db:


